### PR TITLE
Lazily initialize VectorStyleRenderer Worker

### LINKED ISSUE #16271: ReferenceError: Worker is not defined when using WebGLVectorLayerRenderer
**Describe the bug**
I have a JS project with Next JS and when I use a WebGLVectorLayer created as you suggest, I get the following compilation error:

` ⨯ ReferenceError: Worker is not defined
    at __webpack_require__ (/mnt/c/Users/marci/Downloads/DualMaps-main/DualMaps-main/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/mnt/c/Users/marci/Downloads/DualMaps-main/DualMaps-main/.next/server/webpack-runtime.js:33:42)
    at eval (./src/components/Map1.js:15:87)
    at (ssr)/./src/components/Map1.js (/mnt/c/Users/marci/Downloads/DualMaps-main/DualMaps-main/.next/server/app/page.js:140:1)
    at __webpack_require__ (/mnt/c/Users/marci/Downloads/DualMaps-main/DualMaps-main/.next/server/webpack-runtime.js:33:42)
    at eval (./src/app/page.js:10:74)
    at (ssr)/./src/app/page.js (/mnt/c/Users/marci/Downloads/DualMaps-main/DualMaps-main/.next/server/app/page.js:129:1)
    at Object.__webpack_require__ [as require] (/mnt/c/Users/marci/Downloads/DualMaps-main/DualMaps-main/.next/server/webpack-runtime.js:33:42)
digest: "2474330052"
 GET / 500 in 26087ms
`

**To Reproduce**
1. Go to a repository that I created: https://github.com/MarciaBM/openlayers-bug
2. Just run in dev
3. See error in the console

**Expected behavior**
No error

### LINKED ISSUE #16436: "ReferenceError: Worker is not defined" build error on upgrading from 10.2.1 to 10.3.0 and/or 10.3.1
**Describe the bug**
After upgrading our project from 10.2.1 to 10.3.0 and 10.3.1 our test suite fails with the message "ReferenceError: Worker is not defined".
Typical stacktrace points to `webgl.js`:

```
  ● Test suite failed to run

    ReferenceError: Worker is not defined

      1 | import { Map as OlMap } from 'ol';
    > 2 | import { Layer as BaseLayer, Vector as VectorLayer, Group as LayerGroup } from 'ol/layer';
        | ^
      3 | import { Vector as VectorSource, ImageWMS, WMTS, XYZ, TileWMS } from 'ol/source';
      4 | import { LayerManagerModel, LayerTypes } from '../models';
      5 | import { OlLayerHelper } from '../helpers/ol-layer.helper';

      at create (../../node_modules/ol/worker/webgl.js:4:11)
      at Object.<anonymous> (../../node_modules/ol/render/webgl/VectorStyleRenderer.js:23:39)
      at Object.<anonymous> (../../node_modules/ol/renderer/webgl/VectorLayer.js:7:1)
      at Object.<anonymous> (../../node_modules/ol/layer/WebGLVector.js:5:1)
      at Object.<anonymous> (../../node_modules/ol/layer.js:16:1)
      at Object.<anonymous> (src/lib/openlayers-map/open-layers-layer-manager.ts:2:1)
      at Object.<anonymous> (src/lib/openlayers-map/openlayers-map.ts:10:1)
      at Object.<anonymous> (src/lib/map-service/map.service.ts:2:1)
      at Object.<anonymous> (src/lib/map/map.component.ts:2:1)
      at Object.<anonymous> (src/lib/map/map.component.spec.ts:1:1)
```
see eg. https://github.com/Tailormap/tailormap-viewer/actions/runs/12179604586/job/33972116224?pr=772

Note that we don't actually use webgl

**To Reproduce**
1. Go to '[Tailormap/tailormap-viewer](https://github.com/Tailormap/tailormap-viewer)'
2. Check out and run `npm i ol`
3. run tests `npm test`

**Expected behaviour**
At least some indication in the upgrade notes or just a painless upgrade

### PR DESCRIPTION
**Pull request by M393**
Fixes #16271
Fixes #16436

### CODE REVIEW

**Review by jahow — COMMENTED** [review]
Looks good but I'm surprised about the rendering test failures. Do you know where it comes from?

**Comment by M393** [comment]
Probably related to https://github.com/openlayers/openlayers/pull/16459#issuecomment-2540134784

**Comment by ahocevar** [comment]
@jahow Yes, the rendering test failures are unrelated, and would be fixed with #16459. If you'd be up for a review there, I can merge and this pull request can be rebased.

**Review by tschaub — APPROVED** [review]

**Comment by tschaub** [comment]
Thanks, @M393
