### ISSUE TITLE
Errors of ol itself after upgraded to v6.6

### ISSUE THREAD

**Issue by MukeZ** [openlayers/openlayers#12497]
**Describe the bug**
Today I upgraded my app to use ol v6.6.
Then it shows lots of error when I run vue-cli-service serve.
I checked the error messages and they point to the ol library.
For example:
![Capture](https://user-images.githubusercontent.com/9669996/125239585-31e3a200-e32c-11eb-8485-1eb92aae791f.PNG)
Then in EsriJSON.d.ts
![Capture1](https://user-images.githubusercontent.com/9669996/125239624-41fb8180-e32c-11eb-9908-8e9dc0661d67.PNG)

However, they are not affected my app and all functions are still working.

**To Reproduce**
run vue-cli-service serve

**Expected behavior**
It shouldn't have any errors

**Comment by ahocevar** [comment]
Is this with a project authored in TypeScript? This is probably because `@types/arcgis-rest-api` is a `devDependency` in OpenLayers, but should be a `dependency` now that we're including type definitions.

Please try each of the two workarounds below separately and report your findings:

1. In your `tsconfig.json`'s `compilerOptions`, add `"skipLibCheck": "true"`.
2. Install the missing dependency with `npm install --save-dev `@types/arcgis-rest-api`.

**Comment by MukeZ** [comment]
I test them separately and they both work.
But the solution 2 only fix the `arcgis-rest-api` issue

In the EsriJSON.d.ts

`TS2304: Cannot find name 'Feature'.`
![Esri](https://user-images.githubusercontent.com/9669996/125275527-7e41d880-e352-11eb-8d5a-428306cdb4b1.PNG)

In the GeoJSON.d.ts

`TS2307: Cannot find module 'geojson' or its corresponding type declarations.`
`TS2304: Cannot find name 'Feature'.`
![Capture](https://user-images.githubusercontent.com/9669996/125275603-974a8980-e352-11eb-8fd1-f01a012dd3cb.PNG)


In the ImageBase.d.ts 
`TS2694: Namespace '"C:/Works/vue-horizon/node_modules/ol/ImageState"' has no exported member 'default'.`
![imagestate](https://user-images.githubusercontent.com/9669996/125275893-eabcd780-e352-11eb-864d-03fb7640187d.PNG)


In the SimpleGeometry.d.ts
`TS2694: Namespace '"C:/Works/vue-horizon/node_modules/ol/geom/GeometryLayout"' has no exported member 'default'.`
![1](https://user-images.githubusercontent.com/9669996/125276004-0de78700-e353-11eb-9647-d08eab26fe59.PNG)


In the Tile.d.ts
`TS2694: Namespace '"C:/Works/vue-horizon/node_modules/ol/TileState"' has no exported member 'default'.`
![2](https://user-images.githubusercontent.com/9669996/125276011-10e27780-e353-11eb-9be3-76efdb90ccde.PNG)

**Comment by ahocevar** [comment]
Ok, thanks for the test report @MukeZ. In this case, I'd recommend setting `"skipLibCheck": true` in `tsconfig.json`, which is also the default since TypeScript v3.9.

**Comment by mhosman** [comment]
Same issue here!!!

**Comment by ahocevar** [comment]
@mhosman Same recommendation to you: Set `"skipLibCheck": true` in the `"compilerOptions"` of your `tsconfig.json`.

**Comment by yohny** [comment]
I get similar set of errors when trying to compile Angular project using `ol` v6.6.0,  but I have one new - TS2315
```
Error: node_modules/ol/ImageBase.d.ts:32:48 - error TS2694: Namespace '"/home/yohny/web/hh-fe/Frontend/ClientApp/node_modules/ol/ImageState"' has no exported member 'default'.

32     protected state: import("./ImageState.js").default;
                                                  ~~~~~~~


Error: node_modules/ol/Tile.d.ts:131:47 - error TS2694: Namespace '"/home/yohny/web/hh-fe/Frontend/ClientApp/node_modules/ol/TileState"' has no exported member 'default'.

131     protected state: import("./TileState.js").default;
                                                  ~~~~~~~


Error: node_modules/ol/geom/SimpleGeometry.d.ts:27:53 - error TS2694: Namespace '"/home/yohny/web/hh-fe/Frontend/ClientApp/node_modules/ol/geom/GeometryLayout"' has no exported member 'default'.

27     protected layout: import("./GeometryLayout.js").default;
                                                       ~~~~~~~


Error: node_modules/ol/proj/Units.d.ts:7:31 - error TS2315: Type 'Object' is not generic.

7 export const METERS_PER_UNIT: Object<Units, number>;
                                ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ol/source/Cluster.d.ts:110:31 - error TS2314: Generic type 'Feature<Geometry>' requires 1 type argument(s).

110     protected features: Array<Feature>;
                                  ~~~~~~~


Error: node_modules/ol/source/Cluster.d.ts:121:23 - error TS2314: Generic type 'VectorSource<Geometry>' requires 1 type argument(s).

121     protected source: VectorSource;
                          ~~~~~~~~~~~~
```

**Comment by ahocevar** [comment]
Yeah, that's an issue with our string enums, which I'm planning to remove as soon as possible.

But in general, I think using `"skipLibCheck": true` is the way to go, although the Angular default setup does not agree.

**Comment by abakostar** [comment]
Failed to compile.

node_modules/ol/ImageBase.d.ts:32:48 - error TS2694: Namespace '"C:/Devopwebsig/websig-minesec/node_modules/ol/ImageState"' has no exported member 'default'.

32     protected state: import("./ImageState.js").default;
                                                  ~~~~~~~

With angular 11 and openlayers v6.5.0. Just the first compile with a map component

**Comment by abakostar** [comment]
my package.json is there:
{
  "name": "websig-minesec",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.2.14",
    "@angular/common": "~11.2.14",
    "@angular/compiler": "~11.2.14",
    "@angular/core": "~11.2.14",
    "@angular/forms": "~11.2.14",
    "@angular/platform-browser": "~11.2.14",
    "@angular/platform-browser-dynamic": "~11.2.14",
    "@angular/router": "~11.2.14",
    "@types/ol": "^6.5.3",
    "ol": "^6.5.0",
    "ol-layerswitcher": "^3.8.3",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.13",
    "@angular/cli": "~11.2.14",
    "@angular/compiler-cli": "~11.2.14",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.5"
  }
}

**Comment by ahocevar** [comment]
Make sure you have `"skipLibCheck": true` in the `"compilerOptions"` section of your `tsconfig.json`.

**Comment by ineeve** [comment]
I also have an angular project using OpenLayers. Upgraded ol to 6.6 and started seeing the same set of errors as reported by @yohny . Setting `"skipLibCheck": true` in the `"compilerOptions"` solved the issue for now. Thanks @ahocevar :)

**Comment by abakostar** [comment]
Thank you of you. this solutions have solved my problem. Now i know that why Anular signal error  for (@Input() map: Map;) in this instructions 
import { ElementRef, Input } from '@angular/core';
import { Component, OnInit, ChangeDetectionStrategy } from '@angular/core';
import Map from 'ol/Map';

@Component({
  selector: 'app-map',
  template: '',
  styles: [':host { width: 100%; height: 100%; display: block; }',
  ],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class MapComponent implements OnInit {

  @Input() map: Map;
  constructor(private elementRef: ElementRef) {
  }
  ngOnInit() {
    this.map.setTarget(this.elementRef.nativeElement);
  }
}


I am following the tutorial of the address : https://dev.to/camptocamp-geo/openlayers-in-an-angular-application-mn1

The message errors is:
Error: src/app/components/map/map.component.ts:14:12 - error TS2564: Property 'map' has no initializer and is not definitely assigned in the constructor.

14   @Input() map: Map;
              ~~~

**Comment by ankur09011** [comment]
I have a same setup, but I am using docker image `node:14.17.0-stretch-slim`. As mentioned above I added "skipLibCheck": true in the "compilerOptions", but no resolve.

Error: src/app/modules/olmap/classes/click_interactions.ts:515:46 - error TS2339: Property 'getFeatures' does not exist on type 'Object'.

```
515             const selectedFeature = e.target.getFeatures().item(0);
                                                 ~~~~~~~~~~~


Error: src/app/modules/olmap/classes/click_interactions.ts:663:36 - error TS2314: Generic type 'Feature<Geometry>' requires 1 type argument(s).

663             const selectedFeature: OlFeature = e.target.getFeatures().item(0);
                                       ~~~~~~~~~


Error: src/app/modules/olmap/classes/click_interactions.ts:663:57 - error TS2339: Property 'getFeatures' does not exist on type 'Object'.

663             const selectedFeature: OlFeature = e.target.getFeatures().item(0);
                                                            ~~~~~~~~~~~


Error: src/app/modules/olmap/classes/click_interactions.ts:83:34 - error TS2314: Generic type 'Feature<Geometry>' requires 1 type argument(s).

83     private lastClickedBoundary: OlFeature;
                                    ~~~~~~~~~


Error: src/app/modules/olmap/classes/click_interactions.ts:841:50 - error TS2314: Generic type 'Feature<Geometry>' requires 1 type argument(s).

841     private onPopBoundarySelect(selectedFeature: OlFeature) {
                                                     ~~~~~~~~~
```

**Comment by simonseyock** [comment]
For `OlFeature` you need a type argument now. If you don't know the exact type you can just use `OlFeature<Geometry>`

**Comment by ahocevar** [comment]
@ankur09011 These are different issues, because the errors are in your code, not the OpenLayers library. See #12542 for the generic type. For `e.target`, you either need to cast that to the actual type, or reference the instance instead of `e.target`, e.g.
```js
import Select from 'ol/interaction/Select';
const select = new Select({
  // ...
});
select.on('select', e => {
  const selectedFeatureWithCast: OlFeature<Geometry> = (e.target as Select).getFeatures().item(0);
  const selectedFeatureDirect: OlFeature<Geometry> = select.getFeatures().item(0);
});

**Comment by simonseyock** [comment]
For the first error you need to cast the `target` to a feature before accessing it. I.e. `(e.target as OlFeature).getGeometry()`

**Comment by tomgruszowski** [comment]
@ahocevar, are there any best practices for migrating? specifically should we be converting Feature to Feature<T> ? ie Feature<LineString>? The bulk of our errors after removing types/ol seem to center around missing Generics definitions on top of class definitions. What is a bit less obvious is what those T should be sometimes. In example above, I originally changed type from Feature to Feature<Geometry>, but then realized it should be more specific, Feature<LineString | Point> etc. I suppose it's a matter of combing through the details which we took for granted before. But wanted to confirm this is the 'right' path forward to a strongly typed OL app. Thanks!

**Comment by ahocevar** [comment]
For many vector sources, features will be of one specific geometry type. In this case, and if you know beforehand, it is best to use that type as parameter. The benefit is that when working with the geometries of the features in your app, you get type aid for the specific geometry type. If you don’t care because your code does interact with the geometries, you can use `Geometry`.

Does that help?

**Comment by boeckMt** [comment]
Reading [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) and the discussion on https://github.com/formium/tsdx/issues/529, whit the comments https://github.com/formium/tsdx/issues/529#issuecomment-598304924 and https://github.com/formium/tsdx/issues/529#issuecomment-598872250 I think `skipLibCheck: true` is more a temporary fix for this Issue, because the errors reported from 
- https://github.com/openlayers/openlayers/issues/12497#issuecomment-878178445
- https://github.com/openlayers/openlayers/issues/12497#issuecomment-879323368
- https://github.com/openlayers/openlayers/issues/12497#issuecomment-880950001
- ...

should normally helpful to find undiscovered Issues. So if everyone is using `skipLibCheck`, only the developers of `openlayers` can find such errors. I don't know if this is the desired approach?

**Comment by ahocevar** [comment]
Using `"skipLibCheck": true` is the solution, not a workaround.

The reasons for the aforementioned type check complaints are twofild:
* There is some loss of information in the generated d.ts files that ship with the `ol` package. The CI of the library runs type checks directly on the JavaScript code base, so it does not suffer from this loss of information and performs better informed type checks.
* `@types/*` packages (e.g. `@types/geojson`) in OpenLayers are development dependencies, because only the library code needs to be checked when making changes to the library. If your application has `"skipLibCheck": true` configured, it also needs these `@types/*` packages, which does not make sense when you do not work with e.g. GeoJSON objects directly.

In general, a sane approach for an application is to trust its dependencies to be properly typed. So it is not necessary for an application to type check its dependencies. This is also the reason why the default for `skipLibCheck` is `true`.

**Comment by tomgruszowski** [comment]
> For many vector sources, features will be of one specific geometry type. In this case, and if you know beforehand, it is best to use that type as parameter. The benefit is that when working with the geometries of the features in your app, you get type aid for the specific geometry type. If you don’t care because your code does interact with the geometries, you can use `Geometry`.
> 
> Does that help?

@ahocevar I think it helps yes, so to paraphrase myself one more time, is Feature < T > the way to go? and avoid simply using Feature (without the generic) as seemed to work before with @types/ol typings?

**Comment by ahocevar** [comment]
@tomgruszowski With TypeScript, just using `Feature` as type won't work any more anyway. If you don't care, you can now simply use `Feature<Geometry>`. For more convenience, when you know your geometry types beforehand, use them as parameter, e.g. `Feature<Point>`.

**Comment by vaishnavravi33** [comment]
I added "skipLibCheck": true in tsconfig but still getting the error - "Generic type 'Feature<Geometry>' requires 1 type argument(s).ts".

Technology stack is -
Angular v13
OpenLayer 6.9.0
Node v19.4.0
NPM v9.2.0

Please help in this matter.

<img width="719" alt="image" src="https://github.com/openlayers/openlayers/assets/24837842/18c39d0f-47d5-44d4-8960-7d8a56e34394">

**Comment by ahocevar** [comment]
@vaishnavravi33  Please update to a more recent version - types have been improved a lot since v6.9.

**Comment by vaishnavravi33** [comment]
> @vaishnavravi33 Please update to a more recent version - types have been improved a lot since v6.9.
> 
> To fix this one issue in v6.9, just use e.g. `Feature<Geometry>` as type, instead of `Feature`.

Thank you for the quick response.

Another error is similar to open layer feature error, please find the attached screenshot.

<img width="840" alt="image" src="https://github.com/openlayers/openlayers/assets/24837842/061d8419-fd6d-43e5-a41b-2a6d284014a8">

Will have the similar solution as suggested previously, In short I need to update the Open Layer Feature and Layer classes, am I right?

**Comment by ahocevar** [comment]
You can simply `npm install ol@latest` and follow the [upgrade notes](https://github.com/openlayers/openlayers/blob/main/changelog/upgrade-notes.md).

**Comment by vaishnavravi33** [comment]
> > @vaishnavravi33 Please update to a more recent version - types have been improved a lot since v6.9.
> > To fix this one issue in v6.9, just use e.g. `Feature<Geometry>` as type, instead of `Feature`.
> 
> Thank you for the quick response.
> 
> Another error is similar to open layer feature error, please find the attached screenshot.
> 
> <img alt="image" width="840" src="https://user-images.githubusercontent.com/24837842/283470637-061d8419-fd6d-43e5-a41b-2a6d284014a8.png">
> Will have the similar solution as suggested previously, In short I need to update the Open Layer Feature and Layer classes, am I right?

In previous version of angular and open layer I was able to extend the "VectorLayer" and able to add the feature in it but with latest version of it is giving the error.

For Example -
```
export class baseLayer extends VectorLayer  {
    constructor() {
        super();
        this.createBaseLayer();
    }
	
	private createBaseLayer() {
        let features = [];
        
        const feature = new baseFeature();
        featuress.push(feature);

        super.setProperties({
            source: new VectorSource({
                features: features
            })
        });
    }
	
	getFeatures() {
        return super.getSource().getFeatures();
    }

    getSource() {
        return super.getSource();
    }
}
```
When I update the "vectorlayer" to "VectorSource<any>" gives another error in the above mentioned code.
I have existing working open layer code and just recently updated the angular version and now getting too much errors of the open layer code.

Is there any minimal fix is available, If yes please suggest. Thanks.

**Comment by ahocevar** [comment]
I don't see why you wouldn't be able to extend `VectorLayer`. TypeScript is giving you the necessary hints. This will work:
```ts
export class baseLayer extends VectorLayer<VectorSource> {
}
```

**Comment by rcollette** [comment]
Adding skipLibCheck is simply a workaround to an incorrectly defined type.  All one has to do is open the type declaration file and the error is there.
![image](https://github.com/openlayers/openlayers/assets/136476/dbee6314-c178-40ab-abae-80a4cf743385)

```
Error: node_modules/ol/layer/VectorImage.d.ts:165:35 - error TS2344: Type 'VectorSource<FeatureType>' does not satisfy the constraint 'VectorSource<Feature<Geometry>>'.
  Types of property 'setLoader' are incompatible.
    Type '(loader: FeatureLoader<FeatureType>) => void' is not assignable to type '(loader: FeatureLoader<Feature<Geometry>>) => void'.
      Types of parameters 'loader' and 'loader' are incompatible.
        Types of parameters 'arg4' and 'arg4' are incompatible.
          Type '(arg0: FeatureType[]) => void' is not assignable to type '(arg0: Feature<Geometry>[]) => void'.
            Types of parameters 'arg0' and 'arg0' are incompatible.
              Type 'Feature<Geometry>[]' is not assignable to type 'FeatureType[]'.
                Type 'Feature<Geometry>' is not assignable to type 'FeatureType'.
                  'Feature<Geometry>' is assignable to the constraint of type 'FeatureType', but 'FeatureType' could be instantiated with a different subtype of constraint 'Feature<Geometry>'.

```

**Comment by rcollette** [comment]
@ahocevar 9.2.4

**Comment by ahocevar** [comment]
Yes, this was a known issue in 9.2.4 and is fixed in dev.
