### ISSUE TITLE
VectorImage type declaration errors

### ISSUE THREAD

**Issue by rcollette** [openlayers/openlayers#15897]
**Describe the bug**
There is a type declaration inconsistency in VectorImage.d.ts

The bug prevents compilation of dependent code when the Typescript compiler option skipLibCheck=false

**To Reproduce**
Using Typescript 5.1.6
Open the file ol/layer/VectorImage.d.ts in WebStorm

See the error:
```
Error: node_modules/ol/layer/VectorImage.d.ts:165:35 - error TS2344: Type 'VectorSource<FeatureType>' does not satisfy the constraint 'VectorSource<Feature<Geometry>>'.
  Types of property 'setLoader' are incompatible.
    Type '(loader: FeatureLoader<FeatureType>) => void' is not assignable to type '(loader: FeatureLoader<Feature<Geometry>>) => void'.
      Types of parameters 'loader' and 'loader' are incompatible.
        Types of parameters 'arg4' and 'arg4' are incompatible.
          Type '(arg0: FeatureType[]) => void' is not assignable to type '(arg0: Feature<Geometry>[]) => void'.
            Types of parameters 'arg0' and 'arg0' are incompatible.
              Type 'Feature<Geometry>[]' is not assignable to type 'FeatureType[]'.
                Type 'Feature<Geometry>' is not assignable to type 'FeatureType'.
                  'Feature<Geometry>' is assignable to the constraint of type 'FeatureType', but 'FeatureType' could be instantiated with a different subtype of constraint 'Feature<Geometry>'.
```

**Expected behavior**
There should be no type errors.   I should be able to build an application with typescript skipLibCheck option set to false.

**Comment by ahocevar** [comment]
Do you get this with the latest dev version? `npm install ol@dev`? This looks like an issue we have fixed recently.

**Comment by rcollette** [comment]
It is in 9.2.4

I tried dev and I get some errors but we were upgrading from a very old release.   

```
Error: src/app/usecases/spatial.module/map/map.service.ts:25:49 - error TS2344: Type 'Feature<Geometry>' does not satisfy the constraint 'VectorSource<never>'.
  Type 'Feature<Geometry>' is missing the following properties from type 'VectorSource<never>': loader_, format_, overlaps_, url_, and 64 more.

25   private readonly vFeatureOverlay: VectorLayer<Feature>;
                                                   ~~~~~~~


Error: src/app/usecases/spatial.module/map/map.service.ts:46:5 - error TS2322: Type 'VectorLayer<VectorSource<never>, never>' is not assignable to type 'VectorLayer<Feature<Geometry>, never>'.
  Type 'VectorSource<never>' is missing the following properties from type 'Feature<Geometry>': id_, geometryName_, style_, styleFunction_, and 13 more.

46     this.vFeatureOverlay = new VectorLayer({
       ~~~~~~~~~~~~~~~~~~~~


Error: src/app/usecases/spatial.module/map/map.service.ts:77:44 - error TS2339: Property 'clear' does not exist on type 'Feature<Geometry>'
```

**Comment by schubertf** [comment]
Am seeing a similar but not identical error when upgrading to 9.2.4.

```
node_modules/ol/layer/VectorImage.d.ts:161:140 - error TS2344: Type 'VectorSource<FeatureType>' does not satisfy the constraint 'VectorSource<FeatureLike> | VectorTile<FeatureLike>'.
  Type 'VectorSource<FeatureType>' is not assignable to type 'VectorSource<FeatureLike>'.
    Types of property 'setLoader' are incompatible.
      Type '(loader: FeatureLoader<FeatureType>) => void' is not assignable to type '(loader: FeatureLoader<FeatureLike>) => void'.
        Types of parameters 'loader' and 'loader' are incompatible.
          Types of parameters 'arg4' and 'arg4' are incompatible.
            Type '((arg0: FeatureType[]) => void) | undefined' is not assignable to type '((arg0: FeatureLike[]) => void) | undefined'.
              Type '(arg0: FeatureType[]) => void' is not assignable to type '(arg0: FeatureLike[]) => void'.
                Types of parameters 'arg0' and 'arg0' are incompatible.
                  Type 'FeatureLike[]' is not assignable to type 'FeatureType[]'.
                    Type 'FeatureLike' is not assignable to type 'FeatureType'.
                      'FeatureType' could be instantiated with an arbitrary type which could be unrelated to 'FeatureLike'.

161 declare class VectorImageLayer<FeatureType extends import("../Feature.js").default<import("../geom.js").Geometry>> extends BaseVectorLayer<import("../source/Vector.js").default<FeatureType>, CanvasVectorImageLayerRenderer> {
```

Is this because of the same issue?

**Comment by ahocevar** [comment]
Yes, @schubertf. Please use `ol@dev` for now, where this is fixed.

**Comment by steuic** [comment]
I've got same issue (https://github.com/openlayers/openlayers/issues/15897#issue-2340680684) when compiling OpenLayers 9.2.4 with TypeScript 5.1.6 (inside an Angular 16 project).
I was upgrading from 8.2.0.

Error:
```
node_modules/ol/layer/Vector.d.ts:172:108 - error TS2344: Type 'VectorSource<FeatureType>' does not satisfy the constraint 'VectorSource<FeatureLike> | VectorTile<FeatureLike>'.
  Type 'VectorSource<FeatureType>' is not assignable to type 'VectorSource<FeatureLike>'.
    Types of property 'setLoader' are incompatible.
      Type '(loader: FeatureLoader<FeatureType>) => void' is not assignable to type '(loader: FeatureLoader<FeatureLike>) => void'.
        Types of parameters 'loader' and 'loader' are incompatible.
          Types of parameters 'arg4' and 'arg4' are incompatible.
            Type '((arg0: FeatureType[]) => void) | undefined' is not assignable to type '((arg0: FeatureLike[]) => void) | undefined'.
              Type '(arg0: FeatureType[]) => void' is not assignable to type '(arg0: FeatureLike[]) => void'.
                Types of parameters 'arg0' and 'arg0' are incompatible.
                  Type 'FeatureLike[]' is not assignable to type 'FeatureType[]'.
                    Type 'FeatureLike' is not assignable to type 'FeatureType'.
                      'FeatureLike' is assignable to the constraint of type 'FeatureType', but 'FeatureType' could be instantiated with a different subtype of constraint 'FeatureLike'.
                        Type 'RenderFeature' is not assignable to type 'FeatureType'.
                          'RenderFeature' is assignable to the constraint of type 'FeatureType', but 'FeatureType' could be instantiated with a different subtype of constraint 'FeatureLike'.

172 declare class VectorLayer<FeatureType extends import("../Feature.js").FeatureLike> extends BaseVectorLayer<import("../source/Vector.js").default<FeatureType>, CanvasVectorLayerRenderer> {
```

Switching to ol@dev (`9.2.5-dev.1720379541433` actually).
Thank you @ahocevar

**Comment by arashmad** [comment]
> **Describe the bug** There is a type declaration inconsistency in VectorImage.d.ts
> 
> The bug prevents compilation of dependent code when the Typescript compiler option skipLibCheck=false
> 
> **To Reproduce** Using Typescript 5.1.6 Open the file ol/layer/VectorImage.d.ts in WebStorm
> 
> See the error:
> 
> ```
> Error: node_modules/ol/layer/VectorImage.d.ts:165:35 - error TS2344: Type 'VectorSource<FeatureType>' does not satisfy the constraint 'VectorSource<Feature<Geometry>>'.
>   Types of property 'setLoader' are incompatible.
>     Type '(loader: FeatureLoader<FeatureType>) => void' is not assignable to type '(loader: FeatureLoader<Feature<Geometry>>) => void'.
>       Types of parameters 'loader' and 'loader' are incompatible.
>         Types of parameters 'arg4' and 'arg4' are incompatible.
>           Type '(arg0: FeatureType[]) => void' is not assignable to type '(arg0: Feature<Geometry>[]) => void'.
>             Types of parameters 'arg0' and 'arg0' are incompatible.
>               Type 'Feature<Geometry>[]' is not assignable to type 'FeatureType[]'.
>                 Type 'Feature<Geometry>' is not assignable to type 'FeatureType'.
>                   'Feature<Geometry>' is assignable to the constraint of type 'FeatureType', but 'FeatureType' could be instantiated with a different subtype of constraint 'Feature<Geometry>'.
> ```
> 
> **Expected behavior** There should be no type errors. I should be able to build an application with typescript skipLibCheck option set to false.


Same issue here.

Here is my code to define a custom type
```typescript
import { OSM, XYZ, Vector as VectorSource } from "ol/source";
import { Tile as TileLayer, Vector as VectorLayer } from "ol/layer";

/* Type => Layers supported by map */
export type TypeLayer = TileLayer<OSM | XYZ> | VectorLayer<VectorSource>;
```

By updating the `ol` package to the latest version (`^9.1.0`), I got the same issue. Here is TS and OL versions cause conflict:
```
"ol": "^9.1.0",
"typescript": "^5.1.3",
```

After trying many things, I couldn't figure it out so I scaled down to `^8.2.0` and it worked again.

Any solution or suggestion?

**Comment by ahocevar** [comment]
v10.0.0 has been released with the fix, closing.

**Comment by bad-ch** [comment]
OL v10.2.1 and typescript v5.3.3 I get still the error " Type 'VectorSource<Feature<Geometry>>' is missing the following properties from type 'Feature<Geometry>': id_, geometryName_, style_, styleFunction_, and 13 more.ts(2344)" for a VectorImageLayer, any ideas ?
