### ISSUE TITLE
Graticule example is broken

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#8434]
on master, the example is broken, the error is:
```
Uncaught TypeError: point.setCoordinates is not a function
    at Graticule.getMeridianPoint_ (Graticule.js:368)
    at Graticule.addMeridian_ (Graticule.js:339)
    at Graticule.createGraticule_ (Graticule.js:470)
    at Graticule.handlePostCompose_ (Graticule.js:642)
    at Map.boundListener (events.js:41)
    at Map.dispatchEvent (EventTarget.js:95)
    at CanvasMapRenderer.dispatchComposeEvent_ (Map.js:89)
    at CanvasMapRenderer.renderFrame (Map.js:167)
    at Map.renderFrame_ (PluggableMap.js:1218)
    at Map.<anonymous> (PluggableMap.js:191)
```

**Comment by ahocevar** [comment]
Did you investigate what broke this?

**Comment by fredj** [comment]
I think that the bug was introduced in c0d04ea0778, we had something like:
```
this.meridiansLabels_[index].geom : new Point(null)
```
And it was changed to: 
```
point = this.meridiansLabels_[index];
point.setCoordinates(coordinate);
```

**Comment by ahocevar** [comment]
Thanks for the investigation and the fix @fredj.
