### ISSUE TITLE
labels for ol.Graticule

### ISSUE THREAD

**Issue by gastonmz** [openlayers/openlayers#3210]
Hey, 

I migrated from OL2 to OL3 on my app and realize that ol.Graticule have not more support for labels!?
How can I fix it asap?

Thanks a lot! 
Gaston

PS: I love OL! is the best map tool I ever  use

**Comment by elemoine** [comment]
Sorry, this is not supported for the moment. A PR would be welcome. Alternatively you could fund this work.

**Comment by bill-chadwick** [comment]
As it stands the graticule is only for an EPSG:4326 lat/lon grid. I am attempting to generalise it so that it will draw grids for other projections such as EPSG:27700 (British Grid) or UTM. I am doing this by giving the graticule a projection property itself - defaulting to EPSG:4326. I will post a link to an example when I am done.

**Comment by bill-chadwick** [comment]
My demo is here

http://www.bdcc.co.uk/ol3/examples/os-graticule.html

It shows both a UK Grid graticule and a WGS84 Lat/Lon graticule. Still no labels I am afraid.

This uses a re-worked graticule.js that can draw a Lat/Lon graticule on a 'view' of any projection or a 'view' projection graticule. I have tried to limit the number of graticule lines drawn. Performance of the demo is good at all zooms.

TODO is an arbitrary projection graticule on an arbitrary projection view. e.g. an EPSG:27700  (UK) graticule on an EPSG:3857 (Web Mercator) view.

**Comment by bill-chadwick** [comment]
The original graticule demo (EPSG:4326 graticule on EPSG:3857 map) using the new graticule code is here

http://www.bdcc.co.uk/ol3/examples/graticule.html

it looks to be working fine at all zooms and locations.

**Comment by mackenrou** [comment]
Hi  @bill-chadwick 

I'm working on app what uses ol 3.0.0 and i need to add a graticule with labels.

I know that labels are not yet available. 

But i see your example and you use 'on' method with "graticule.on('change', ...".
I wrote a similar code and i need to use 'on' method but it is missing. I get error "undefined is not a function"

I don't see 'on' method in graticule.js from ol.
What is the problem?

Thanks in advance

**Comment by mackenrou** [comment]
I'm sorry. I did not understand you had customized the graticule.js.

I tried your graticule and get nothing when I define a UTM projection such as:
"+proj=utm +zone=30 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

With proj=longlat is fine.

**Comment by bill-chadwick** [comment]
My customisation is pretty old now. It relies on modifications to a few
other .js files.
Did you look at the demos on www.bdcc.co.uk ?

Bill

**Comment by kevin4z** [comment]
Is it possible to display fictitious graticule labels now? :)

**Comment by ahocevar** [comment]
Fixed with #6737.
