### ISSUE TITLE
Angular cli webpack prod build error

### ISSUE THREAD

**Issue by hei-pa** [openlayers/openlayers#8815]
I want to build an Angular app with ol. Non production build is working but prod build results in runtime error.

Same result with Angular 6 and typescript 2.9.2

![image](https://user-images.githubusercontent.com/3512352/46904124-cc92c600-cedf-11e8-977b-2f1026702fdf.png)

```json
{
  "name": "ol-test",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.0.0-beta.5",
    "@angular/common": "~7.0.0-beta.5",
    "@angular/compiler": "~7.0.0-beta.5",
    "@angular/core": "~7.0.0-beta.5",
    "@angular/forms": "~7.0.0-beta.5",
    "@angular/http": "~7.0.0-beta.5",
    "@angular/platform-browser": "~7.0.0-beta.5",
    "@angular/platform-browser-dynamic": "~7.0.0-beta.5",
    "@angular/router": "~7.0.0-beta.5",
    "core-js": "^2.5.4",
    "ol": "^5.2.0",
    "rxjs": "~6.3.2",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.9.0-beta.1",
    "@angular/cli": "~7.0.0-beta.3",
    "@angular/compiler-cli": "~7.0.0-beta.5",
    "@angular/language-service": "~7.0.0-beta.5",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.1"
  }
}
```

```typescript
import { Component } from '@angular/core';
import Map from 'ol/Map';
import View from 'ol/View';
import TileLayer from 'ol/layer/Tile';
import XYZ from 'ol/source/XYZ';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  ngOnInit() {

    new Map({
      target: 'map',
      layers: [
        new TileLayer({
          source: new XYZ({
            url: 'https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png'
          })
        })
      ],
      view: new View({
        center: [0, 0],
        zoom: 2
      })
    });

  }

}

```

**Comment by smithk58** [comment]
Noting that upgrading to Angular 7 did fix the prod build issue tracked in another ticket, but this issue is still happening.

Angular 7, Typescript 3.1.3

**Comment by andreasrueedlinger** [comment]
I noticed the same error and figured out that `addCommon` in `ol/proj` is just optimized away by angular-cli in production mode.
As a workaround you can import `addCommon` from `ol/proj` and call it in your initialization code but I suspect that this is just the tip of the iceberg...

**Comment by ArgV04** [comment]
I am also running into this issues with Angular 7.0.1 when running a prod build and have set **buildOptimizer** set to **true** in _**angular.json**_, when set **buildOptimizer** to false for prod builds it works. But is there any better solution?

**Comment by yohny** [comment]
I believe this is the same as #8859

**Comment by Chris1234567899** [comment]
Any update on this? This seems quite important.

**Comment by yohny** [comment]
related issue in angular-cli project was closed - see [this comment](https://github.com/angular/angular-cli/issues/12760#issuecomment-436612737) - looks like openlayers'  `package.json` is incorrectly identifying `sideEffects` and therefore some parts are optimized away

**Comment by OSHistory** [comment]
@fredj 
I can confirm, that this works with newest angular (7.0.4) and ol 5.3.0.
I have not tried with older versions of either angular or ol. 

Thanks for your effort in the matter.

**Comment by ArgV04** [comment]
> Sorry but I cannot confirm that this is solved. Using ol 5.3 and Angular 7.0.3 I still run into this issue.

YES ... STILL issue occurs! Please REOPEN!

**Comment by ahocevar** [comment]
This was fixed after v5.3.0.

**Comment by ArgV04** [comment]
Then we need a newer version update for ol :)

**Comment by OSHistory** [comment]
I created a repository using latest @angular/cli (7.0.4 available since 10 days, now at 7.0.5).

https://www.npmjs.com/package/@angular/cli
 
https://github.com/OSHistory/ng7-ol5-demo

On a fresh install the production build gives the same error message in 
the console as above (first post). Including proj.js to sideEffects in 
the package.json resolves the issue.

**Comment by OSHistory** [comment]
BTW, I am sorry about the mixup regarding version reporting (referring to cli).
However it works with the following setup: 

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.0.5
Node: 8.11.3
OS: linux x64
Angular: 7.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.5
@angular-devkit/build-angular     0.10.5
@angular-devkit/build-optimizer   0.10.5
@angular-devkit/build-webpack     0.10.5
@angular-devkit/core              7.0.5
@angular-devkit/schematics        7.0.5
@angular/cli                      7.0.5
@ngtools/webpack                  7.0.5
@schematics/angular               7.0.5
@schematics/update                0.10.5
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
    

While trying to upgrade to version 5 in a project I discovered there might 
might be an issue, when using ol in a angular library. I will extend  the 
repo to mimick a simple integration library.

**Comment by OSHistory** [comment]
I extended the repo and indeed i got the same error as in my previous upgrade efforts: 

~~~
main.a6548f012cdeb04a89a4.js:1 ERROR TypeError: Cannot read property 'getCode' of null
    at jl (main.a6548f012cdeb04a89a4.js:1)
    at Gl (main.a6548f012cdeb04a89a4.js:1)
    at Vl (main.a6548f012cdeb04a89a4.js:1)
    at Nl (main.a6548f012cdeb04a89a4.js:1)
    at t.ngOnInit (main.a6548f012cdeb04a89a4.js:1)
    at main.a6548f012cdeb04a89a4.js:1
    at main.a6548f012cdeb04a89a4.js:1
    at Ma (main.a6548f012cdeb04a89a4.js:1)
    at ru (main.a6548f012cdeb04a89a4.js:1)
    at Object.updateDirectives (main.a6548f012cdeb04a89a4.js:1)
sr @ main.a6548f012cdeb04a89a4.js:1
~~~~

I updated the demo repo, in order to reproduce: 

~~~
npm run build_lib
~~~

then build the application. 

The working standalone build is now under branch standaloneBuild

**Comment by OSHistory** [comment]
Update: 
Having cloned the repository on my second machine, everything worked. The 
aforementioned error no longer occurs on either machine (maybe some build artefacts in memory 
are to blame?).

**Comment by ArgV04** [comment]
Still not working with ol v5.3.0. When a new ol version is expected?

**Comment by anthonymougin** [comment]
Still not working for me :

Angular CLI: 7.0.7
Node: 10.12.0
OS: win32 x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1

Work fine with buildOptimizer: false

**Comment by ahocevar** [comment]
See https://github.com/openlayers/openlayers/issues/9019#issuecomment-444441291 for a workaround.
