### ISSUE TITLE
Included typings do not work correctly

### ISSUE THREAD

**Issue by MichalK6677** [openlayers/openlayers#10871]
I've been using types from DefinitelyTyped 
(https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ol) and all worked fine.

It wants to use new OL included typings in 6.3.0 and ignores the DefinitelyTyped typings. The included types does not work correctly.

Example of included types:
![image](https://user-images.githubusercontent.com/3100059/78376584-d37b3000-75ce-11ea-8d60-f1074b4f083a.png)

Comparsion between OL types and DefinitelyTyped types
![image](https://user-images.githubusercontent.com/3100059/78376799-1e954300-75cf-11ea-85cb-39650cede9db.png)

How can I use the OL types in this example where DefinitelyTyped typings are used:
```
this.draw = new Draw({
	source: this.source,
	type: GeometryType.POINT,
	snapTolerance: 6,
	stopClick: true
});
```
There are many types like this.

How can I exclude/ignore the included types and use types from https://github.com/DefinitelyTyped? 
I have angular application with tsconfig.json. I've tried ignore section in tsconfig.json but it does not help.
![image](https://user-images.githubusercontent.com/3100059/78377481-f528e700-75cf-11ea-8647-38b6121b2364.png)

**Comment by jeroenvheel** [comment]
I also have the same issue I can’t compile the code with 6.3.0

**Comment by mhosman** [comment]
Same issue here!

**Comment by ahocevar** [comment]
Try to add the following to the `compilerOptions` section of `tsconfig.json`:
```json
  "skipLibCheck": true

**Comment by mhosman** [comment]
Hey @ahocevar this is a workaround or a required option from now on?

**Comment by MichalK6677** [comment]
@ahocevar 
I've tried 
```
"skipLibCheck": true,
```
and
```
"skipDefaultLibCheck": true,
```

It did not help. There are still errors in imports because it still does not take it from DefinitelyTyped.
![image](https://user-images.githubusercontent.com/3100059/78400599-51ebc800-75f7-11ea-80e6-09fb279c939d.png)

**Comment by ahocevar** [comment]
@mhosman It depends on the TypeScript version you are using.

@MichalK6677 The inofficial types from DefinitelyTyped were manually created for older versions of OpenLayers, so some of them will very likely be incompatible. My advice would be to update your code to work with the types that ship with OpenLayers when upgrading to v6.3.

**Comment by MichalK6677** [comment]
@ahocevar I would like to update my code but the new types included in 6.3.0 seems to be incomatible as you can see my example above in the first post. How can I rewrite the code example with the new type? Property type of Draw object should be string but the new types force my to use an object (check error frok visual studio on image above).

**Comment by kekel87** [comment]
Same here, I got `Cannot use namespace 'GeometryType' as a type.`.

Also, no events type is exported as : `DrawEvent`, `SelectEvent`, ...

I think it would be nice to work with [hanreev/types-ol](https://github.com/hanreev/types-ol), he's done a lot of work on Openlayer typing, and it works very well!

**Comment by ahocevar** [comment]
That type for `ol/interaction/Draw` was indeed incorrectly generated.

We currently do not export event types intentionally, because we decided a few years ago that the `type` argument in our events is a plain string. How we proceed further here depends on what TypeScript users want. We can remove the .d.ts types from future versions again, or we can continue with type auto-generation and accept that there are some kinks until TypeScript's support for JSDoc types improves. If we do the latter, it may make sense to start requiring enums for event types when TypeScript properly supports them.

**Comment by MichalK6677** [comment]
@ahocevar I still do not know how to use it. 
Compilation errors:
![image](https://user-images.githubusercontent.com/3100059/78451137-eef44280-7683-11ea-9444-dca3e67abad5.png)

Is this a valid syntax?
![image](https://user-images.githubusercontent.com/3100059/78451173-2367fe80-7684-11ea-8fb2-f87e2056c894.png)

I am using typescript "typescript": "3.8.3".

**Comment by Siedlerchr** [comment]
I can confirm that the new patched version works now (using TS 3.8) . It fortunately still works with the types from https://github.com/hanreev/types-ol

This is now my workaround for having types in an Angular project

**Comment by tomgruszowski** [comment]
> I can confirm that the new patched version works now (using TS 3.8) . It fortunately still works with the types from https://github.com/hanreev/types-ol
> 
> This is now my workaround for having types in an Angular project

@Siedlerchr can you expand on what exactly is required for Angular? is it just adding "skipLibCheck": true? I'm unfamiliar with hanreev's typings package, is that an alternative or do you include that as well?

**Comment by MichalK6677** [comment]
@tomgruszowski 
I use openlayers types from DefinitelyTyped package. It's just about installing npm package "@types/ol": "6.2.0" and types should work without any settings.

**Comment by Siedlerchr** [comment]
@tomgruszowski  I do exactly the same as @MichalK6677. Works fine.  The types from  hanreev are synced with the official DefinitelyTyped repo.

**Comment by tomgruszowski** [comment]
Thank @Siedlerchr and @MichalK6677, I guess I was looking to use the new built in types as types/ol may not be the most accurate (another issue mentioned this).

@ahocevar are you waiting for some TS 3.9 feature, for apps to use that version, so they can properly use native OL typings? or is 3.9 purely for your internal build purposes?

Can we simply use the 'skipLibCheck' flag as you suggested in an earlier comment if our apps are running on TS 3.8.x? and NOT use types/ol.

**Comment by ahocevar** [comment]
@tomgruszowski We are waiting for microsoft/TypeScript#33575 to be fixed, which is currently assigned to the 3.9 milestone. When that is fixed, we can re-evaluate if the auto-generated types are suitable. But in that process, we will need to make some changes in the library so event listeners get the correct types.

**Comment by tomgruszowski** [comment]
> @tomgruszowski We are waiting for [microsoft/TypeScript#33575](https://github.com/microsoft/TypeScript/issues/33575) to be fixed, which is currently assigned to the 3.9 milestone. When that is fixed, we can re-evaluate if the auto-generated types are suitable. But in that process, we will need to make some changes in the library, e.g. so event listeners get the correct types (see [#10885 (comment)](https://github.com/openlayers/openlayers/pull/10885#issuecomment-609599704)).

Thanks, is the 3.9 dependency/fix on your end to generate correct typings/jsdocs or on the app that's going to be using OL?

**Comment by ahocevar** [comment]
> Thanks, is the 3.9 dependency/fix on your end to generate correct typings/jsdocs or on the app that's going to be using OL?

On our end.

**Comment by tomgruszowski** [comment]
@ahocevar any thoughts on this issue? seems like that TypeScript issue keeps getting pushed out each release, now moved to 4.0.1

**Comment by ahocevar** [comment]
@tomgruszowski Until the TypeScript issue is fixed, since we removed the typings from the package, you are free to either use our recommended solution from the README, or third-party types like the `@types/ol` package.

**Comment by tomgruszowski** [comment]
@ahocevar has anything changed with regards to typings in 6.5? Can we remove @types/ol? Noticed a few updates to TS dependencies in 6.5 release notes including the enum issue being resolved.

**Comment by ahocevar** [comment]
I'm pretty sure there are TypeScript users who are unhappy with the types that are derived from the TypeDoc comments. For IntelliSense in VS Code the types included in the library do their job very well.

That said, I think @types/ol still has its justification for TypeScript users, although there should be no issues any more with the included types derived from the TypeDoc comments.
