### ISSUE TITLE
Cannot find module 'ol/proj' (but all the others are OK)

### ISSUE THREAD

**Issue by xavierpena** [openlayers/openlayers#8037]
**Edit:** I have solved the issue replacing it like this =>

	//import proj from 'ol/proj'; // ! ERROR: Cannot find module 'ol/proj'.
	const proj = (<any>require('ol/proj')).default;

I suspect that the `@types/ol` has an error regarding the type declaration of `'ol/proj'`, which is why `import` wouldn't work.

---

It is imported [as shown in the documentation](https://openlayers.org/workshop/en/basics/geolocation.html). All the [other imports](https://openlayers.org/workshop/en/basics/map.html) work fine.

	import proj from 'ol/proj'; // ! ERROR: Cannot find module 'ol/proj'.
	import ol from 'ol'; // OK
	import 'ol/ol.css'; // OK
	import Map from 'ol/map'; // OK
	import View from 'ol/view'; // OK
	import TileLayer from 'ol/layer/tile'; // OK
	import XYZSource from 'ol/source/xyz'; // OK

This is my `package.json` (notice that I am using Typescript):

	{
	  "name": "MyProject",
	  "private": true,
	  "version": "0.0.0",
	  "devDependencies": {
		"@types/webpack-env": "^1.13.0",
		"aspnet-webpack": "^2.0.1",
		"awesome-typescript-loader": "^3.0.0",
		"bootstrap": "^3.3.6",
		"css-loader": "^0.25.0",
		"event-source-polyfill": "^0.0.7",
		"extract-text-webpack-plugin": "^2.0.0-rc",
		"file-loader": "^0.9.0",
		"isomorphic-fetch": "^2.2.1",
		"jquery": "^3.1.1",
		"style-loader": "^0.13.1",
		"typescript": "^2.2.1",
		"url-loader": "^0.5.7",
		"vue": "^2.2.2",
		"vue-loader": "^11.1.4",
		"vue-property-decorator": "^5.0.1",
		"vue-router": "^2.3.0",
		"vue-template-compiler": "^2.2.2",
		"webpack": "^2.2.0",
		"webpack-hot-middleware": "^2.12.2",
		"ol": "^4.6.5", <============= this library
		"@types/ol": "^4.6.1", <====== typescript types
	  }
	}

These are the contents of `.\node_modules\ol`. The file `proj.js` is present there.

Although there is also a folder `\proj` that I suspect could be a problem. If I write `import proj4 from 'ol/proj/proj4';` (<= `.\ol\proj\proj4.js`) it works fine. But I need `'ol/proj'` instead of that.

**Update:** the module resolution [seems to be coherent with the standards](http://www.typescriptlang.org/docs/handbook/module-resolution.html). The subfolder should not be an issue.

	.eslintrc
	array.js
	assertionerror.js
	asserts.js
	attribution.js
	canvasmap.js
	centerconstraint.js
	collection.js
	collectioneventtype.js
	color.js
	color.jsdoc
	colorlike.js
	colorlike.jsdoc
	<DIR> control
	control.js
	coordinate.js
	coordinate.jsdoc
	css.js
	deviceorientation.js
	disposable.js
	dom.js
	easing.js
	easing.jsdoc
	<DIR> events
	events.js
	<DIR> extent
	extent.js
	extent.jsdoc
	feature.js
	featureloader.js
	featureloader.jsdoc
	<DIR> format
	functions.js
	geolocation.js
	geolocationproperty.js
	<DIR> geom
	graticule.js
	has.js
	has.jsdoc
	image.js
	imagebase.js
	imagecanvas.js
	imagestate.js
	imagetile.js
	index.js
	<DIR> interaction
	interaction.js
	kinetic.js
	<DIR> layer
	layertype.js
	loadingstrategy.js
	loadingstrategy.jsdoc
	map.js
	mapbrowserevent.js
	mapbrowsereventhandler.js
	mapbrowsereventtype.js
	mapbrowserpointerevent.js
	mapevent.js
	mapeventtype.js
	mapproperty.js
	math.js
	net.js
	obj.js
	object.js
	objecteventtype.js
	observable.js
	ol.css
	overlay.js
	overlaypositioning.js
	package.json
	pluggablemap.js
	plugins.js
	plugintype.js
	<DIR> pointer
	<DIR> proj <========= is this a problem?
	proj.js <============ OK
	readme.md
	<DIR> render
	render.js
	render.jsdoc
	<DIR> renderer
	<DIR> reproj
	reproj.js
	resolutionconstraint.js
	rotationconstraint.js
	size.js
	<DIR> source
	source.jsdoc
	sphere.js
	string.js
	<DIR> structs
	<DIR> style
	style.js
	tile.js
	tilecache.js
	tilecoord.js
	<DIR> tilegrid
	tilegrid.js
	tilequeue.js
	tilerange.js
	tilestate.js
	tileurlfunction.js
	transform.js
	uri.js
	<DIR> vec
	vectorimagetile.js
	vectortile.js
	view.js
	viewhint.js
	viewproperty.js
	<DIR> webgl
	webgl.js
	xml.js

**Comment by sbrunner** [comment]
`ol/proj` is not a module...

You should do e.-g.:  `import Projection from 'ol/proj/Projection.js';`

**Comment by sbrunner** [comment]
Or use named import.
`import * as proj from 'ol/proj';`

**Comment by xavierpena** [comment]
> import * as proj from 'ol/proj';

Using that, Typescript breaks with "Could not find a declaration file for module 'ol/proj'".

> You should do e.-g.: `import Projection from 'ol/proj/Projection.js';`

I was following [the documentation](https://openlayers.org/workshop/en/basics/geolocation.html) which stated `import proj from 'ol/proj';`. Is it up to date?

Also, I scanned the files under `./ol/proj/*.js` to find the function `fromLonLat` and I couldn't find it.

---

PS: un autre lausannois, quelle surprise! 👏

**Comment by bartvde** [comment]
@sbrunner are the named exports not only in the 5 beta series? He is using 4.6.x

**Comment by xavierpena** [comment]
> You can try with: `import {fromLonLat} from 'ol/proj'`

It breaks saying "Could not find a declaration file for module 'ol/proj'", which I think is related to Typescript.

For now it seems that I am stuck with the convoluted and ugly `const proj = (<any>require('ol/proj')).default;` (at least it works).

The surprising thing for me was that all other imports worked perfectly fine.

**Comment by sbrunner** [comment]
@bartvde effectively ;-)

**Comment by martinmcneela** [comment]
@xavierpena your solution works for me 'const proj = (<any>require('ol/proj')).default;'.

Is there any idea when there will be a fix for this so we can use 'import Proj from 'ol/proj'?

**Comment by Abdullah0991** [comment]
I am also stuck at these problem. Thanks @xavierpena .
Any updates from the developers?

**Comment by ahocevar** [comment]
`import proj from 'ol/proj'` works fine with ol 4.6.5. Like @xavierpena said, this appears to be a problem with the typescript definitions, which are not provided by OpenLayers.

In v5.x, there will be named exports for all functions in `ol/proj`, so this issue won't be relevant any more. You can already `npm install ol@beta` to try that.

**Comment by burnquist** [comment]
It don't seem to be up to date ...
You can try with:
import {fromLonLat} from 'ol/proj'
and dirrectly use fromLonLat
@sbrunner thenks solve

**Comment by andreadompe** [comment]
The same problem here

```
"ol": "^5.3.1",
"typescript": "~3.1.3"
```

if i use `import {fromLonLat} from 'ol/proj'`

i get 

`error TS2305: Module '.../node_modules/@types/ol/proj/index' has no exported member 'fromLonLat'.`

**Comment by vahlo** [comment]
@andreadompe  I got the same error as you.

Following this.

**Comment by ahocevar** [comment]
This issue has been closed. The place to take this discussion to is https://github.com/DefinitelyTyped/DefinitelyTyped.
