### ISSUE TITLE
Converting Features to KML gives error as "TypeError: e.toPrecision is not a function"

### ISSUE THREAD

**Issue by alperdincer** [openlayers/openlayers#10611]
Users are drawing features on map and we are trying to export them to KML format. This is working before OL v4, then we upgraded to v5 and when we try to export KML we got "TypeError: e.toPrecision is not a function" error after the code shown below. We also try to update to v6 to check if there is a change but it still gives the same error. 

`         var format = new ol.format.KML(); 
           var kml = format.writeFeatures(features, { 
                dataProjection : 'EPSG:4326', 
                featureProjection : 'EPSG:3857',
                decimals: 6
            });
`

Is there any suggestions to fix this?

**Comment by ahocevar** [comment]
Looks like somewhere in your KML you have an invalid geometry. Can you share more of your code, or a stack trace?

**Comment by richnic** [comment]
The following simple code snippet should work with OpenLayers 6.1.1:

`var features = [new ol.Feature({ geometry: new ol.geom.Point(ol.proj.transform([12.34, 56.78], "EPSG:4326", "EPSG:3857")), name: "Test" })];`
`var format = new ol.format.KML();`
`var kml = format.writeFeatures(features, { dataProjection:'EPSG:4326', featureProjection: "EPSG:3857", decimals: 6 });`

If the code above works, but not your code, then there may be something wrong with the content of your variable "features".

**Comment by alperdincer** [comment]
@ahocevar I can't share more code, because it is a complicated web app, but I can share the stack trace below. But with @richnic 's idea, I got coordinates from the current geometry and create a new feature from them and try to convert it to KML and boom, it works. So there is no problem with geometry but I'm suspicious about the style.

'var newFeature = new ol.Feature( { geometry: new ol.geom.LineString(features[0].getGeometry().getCoordinates()), name: 'test' });'

Stack Trace : 

TypeError: e.toPrecision is not a function ol.js:7:485011
    Dd http://localhost/ol-app/libs/ol5/ol.js?version=20200102:7
    lu http://localhost/ol-app/libs/ol5/ol.js?version=20200102:7
    yu http://localhost/ol-app/libs/ol5/ol.js?version=20200102:7
    vu http://localhost/ol-app/libs/ol5/ol.js?version=20200102:7
    LineStyle http://localhost/ol-app/libs/ol5/ol.js?version=20200102:7
    lu http://localhost/ol-app/libs/ol5/ol.js?version=20200102:7
    yu http://localhost/ol-app/libs/ol5/ol.js?version=20200102:7
    vu http://localhost/ol-app/libs/ol5/ol.js?version=20200102:7
    Style http://localhost/ol-app/libs/ol5/ol.js?version=20200102:7
    lu http://localhost/ol-app/libs/ol5/ol.js?version=20200102:7
    yu http://localhost/ol-app/libs/ol5/ol.js?version=20200102:7
    vu http://localhost/ol-app/libs/ol5/ol.js?version=20200102:7
    Og http://localhost/ol-app/libs/ol5/ol.js?version=20200102:7
    lu http://localhost/ol-app/libs/ol5/ol.js?version=20200102:7
    yu http://localhost/ol-app/libs/ol5/ol.js?version=20200102:7
    vu http://localhost/ol-app/libs/ol5/ol.js?version=20200102:7
    writeFeaturesNode http://localhost/ol-app/libs/ol5/ol.js?version=20200102:7
    writeFeatures http://localhost/ol-app/libs/ol5/ol.js?version=20200102:7
    startListenEvents http://localhost/ol-app/js-ribbon/ui-core.js?version=20200122:274
    jQuery 2

**Comment by ahocevar** [comment]
@alperdincer That stack trace does not help much. Do you have an unminified build, so we can at least see the unmangled function names? Also, please make sure you're not creating invalid geometries for KML export.

**Comment by mike-000** [comment]
It can be reproduced with a text value for stroke width 
e..g. `new ol.style.Stroke({ color: 'red', width: '10'})`
displays a stroke of width 10 (since `ctx.lineWidth = '10';` is valid) but doesn't write in ol.format.KML
The behavoiur of ctx.lineWidth  appears to be equivalent to
` ctx.lineWidth = Number(string) || 1;` so I have added that to #10580

**Comment by alperdincer** [comment]
Dear @ahocevar, I double check the geometry and other things. Everything except symbology is right. 

@mike-000 is right, it is related to symbology applied to features. We create a new feature and get only geometry from the original feature and export is successful with the new feature set.

**Comment by fredj** [comment]
fixed with #10580
