### ISSUE TITLE
I experienced compilation errors when upgrading from 7.5.0 to 8.2.0 or even later

### ISSUE THREAD

**Issue by zhuzhye** [openlayers/openlayers#16336]
I experienced compilation errors when upgrading from 7.5.0 to 8.2.0 or even later,  I also configured the transpileDependencies: ["ol"] option in vue.config.js
![image](https://github.com/user-attachments/assets/6a450638-8a81-4290-8b07-8e58c4a4d750)
![image](https://github.com/user-attachments/assets/5788ae86-df39-427e-9702-fa6ae80baf33)

How should I solve this problem
I would appreciate it if you could help me with this question

**Comment by ahocevar** [comment]
Maybe try
```
  transpileDependencies: ["ol", "color-rgba"],

**Comment by zhuzhye** [comment]
> ```js
> "color-rgba"
> ```
I tried adding "color-rgba" but it didn't solve the problem

**Comment by ahocevar** [comment]
At least the error message should be different than before. If not, check if your vue build setup is correct: https://github.com/vuejs/vue-loader/issues/1411.
