### ISSUE TITLE
Cannot find format module

### ISSUE THREAD

**Issue by MukeZ** [openlayers/openlayers#10886]
Just upgraded from v6.2.1 to 6.3.0

Lots of `Cannot find module 'xxx'.`  showing when I was running my project,
and they all under` /node_modules/ol/format/`

Thanks

**Comment by ahocevar** [comment]
Please provide some example code where this issue occurs.

**Comment by MukeZ** [comment]
It's working with v6.3.1 now,
