### ISSUE TITLE
Error after migrating to 6.15.11

### ISSUE THREAD

**Issue by mhosman** [openlayers/openlayers#13853]
`Cannot find module 'ol/geom/GeometryType' or its corresponding type declarations.`

**Comment by Rskut** [comment]
Had the same problem. Had to uninstall ol and install it again

**Comment by mhosman** [comment]
Thanks @ahocevar !! I'll close this issue.
