### ISSUE TITLE
Quickselect is not a function - dependancy issue?

### ISSUE THREAD

**Issue by rossholdway** [openlayers/openlayers#8051]
Hi,

Not sure if I should be posting this issue here or at https://github.com/mourner/rbush or https://github.com/mourner/quickselect

I'm importing via ES6 imports, and am getting the following error when trying to add new Features to my vector source.
```
TypeError: quickselect is not a function
    at multiSelect (index.js:557)
    at rbush._build (index.js:232)
    at rbush.load (index.js:94)
    at _ol_structs_RBush_.load (rbush.js:75)
    at _ol_source_Vector_.addFeaturesInternal (vector.js:285)
    at _ol_source_Vector_.addFeatures (vector.js:245)
```
It looks like OL has a dependancy on `rbush` which has a dependancy on `quickselect` which is specified in the rbush package.json as `quickselect: "^1.0.1"`. Quickselect was updated a few hours ago to 1.1.0. Using this new version of quickselect (included as a dependancy with an install of OL) I get the above stack trace. However if I specifically install quickselect 1.0.1 I don't and adding features to my vector source works.

I think this could also be somehow related to #7504 (see the latest stack trace with `quickselect is not a function`)

**Comment by ahocevar** [comment]
The 1.1.0 release of quickselect has switched to ES modules. This might require a different Webpack configuration for our test suite (to fix the test failure shown in #7504). And it might also require a different bundler configuration in your application. Maybe someone else can investigate this further and provide more details and a pull request to fix our Webpack configuration.
